import Head from 'next/head'


export default function DefaultLayout({ children }: {children: React.ReactNode}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>{children}</div>
    </>
  )
}
